stages:
  database_load:
    cmd: python3 src/database_load.py
    deps: 
    - src/database_load.py
    - src/utils/data/load.py
    - src/utils/dvc/params.py
    - data/raw
    outs:
    - data/interim/country.csv
    - data/interim/league.csv
    - data/interim/match.csv
    - data/interim/player.csv
    - data/interim/player_attributes.csv
    - data/interim/team.csv
    - data/interim/team_attributes.csv
  player_preprocessing:
    cmd: python3 src/player_preprocessing.py
    deps:
    - src/player_preprocessing.py
    - data/interim/player.csv
    outs:
    - data/interim/player_preprocessed.csv
